# Generated by Django 2.0.2 on 2018-02-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20180210_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_date', models.DateField()),
                ('marriage_end_date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='spouse',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default=True, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marriage',
            name='spouse_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spouse1', to='tree.Person'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='spouse_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spouse2', to='tree.Person'),
        ),
    ]
