# Generated by Django 2.0.2 on 2018-02-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20180210_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=100, null=True)),
                ('ship_embarkation_location', models.CharField(max_length=500, null=True)),
                ('ship_embarkation_date', models.DateField(null=True)),
                ('arrival_location', models.CharField(max_length=500, null=True)),
                ('arrival_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=250, null=True)),
                ('school_location', models.CharField(max_length=250, null=True)),
                ('degree_earned', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='marriage_date',
        ),
        migrations.AddField(
            model_name='marriage',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='marriage',
            name='marriage_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='burial_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='career',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='maiden_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='military_service',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='beginning',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='ending',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='where',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='schoolattendance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='tree.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='immigration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immigrant', to='tree.Immigration'),
        ),
    ]
